apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 3000       # Changed service port to 3000
      targetPort: 5000 # Keep this as the port your app listens on
      nodePort: 32051  # (optional) Change this to your desired node port
