apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort # Use LoadBalancer if on cloud
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 3000       # Service port
      targetPort: 5000 # Flask app's port
      nodePort: 32000  # NodePort (choose a custom port)
